### ISSUE TITLE
KeyError: 'eid'

### ISSUE THREAD

**Issue by nyuszika7h** [blha303/IRCCloud-logger#9]
Something is wrong again...

```pytb
(venv)melon@cadoth:~/IRCCloud-logger$ python logger.py
Tue Aug  2 11:59:53 2016 log started
Traceback (most recent call last):
  File "logger.py", line 405, in <module>
    parseline(line)
  File "logger.py", line 72, in parseline
    f.write(str(line['eid']))
KeyError: 'eid'
```

**Comment by blha303** [comment]
As far as I know that shouldn't happen, based on the current API documentation. I asked the irccloud devs and the residents of the irc channel for this project (I'm no longer maintaining this myself, maybe I should transfer it to someone), waiting for a reply.

**Comment by blha303** [comment]
Can you replace logger.py with the below (bottom) code block, run it (it should crash again), then run this python script:

```
import json
with open("rawlog.json") as f:
    for line in f.readlines():
        if not "eid" in json.loads(line):
            print(line.strip())
```

and paste the output of that?

```
truncated
```

**Comment by Liamraystanley** [comment]
I'm able to replicate, when specifying a cookie, rather than credentials:
```
[lstanley] [~/projects/IRCCloud-logger]$ python logger.py <insert cookie here>
Tue Aug  2 22:04:32 2016 log started
Traceback (most recent call last):
  File "logger.py", line 405, in <module>
    parseline(line)
  File "logger.py", line 72, in parseline
    f.write(str(line['eid']))
KeyError: 'eid'
```

Printing out the line before attempting to parse it leads me to believe that it's failing to auth:
```
[lstanley] [~/projects/IRCCloud-logger]$ python logger.py
Tue Aug  2 22:07:27 2016 log started
{u'message': u'auth', u'success': False}
```

I haven't used cookie auth'ing in the past, so I am unsure if anything has changed unfortunately.

**Comment by blha303** [comment]
I used cookie auth when I tested it yesterday, didn't have an issue. Guess we could catch the auth failure and prompt for user credentials, I'll do that now.

**Comment by blha303** [comment]
Make sure you're using the `session` cookie (not the cfduid), it's formatted like <number>.<hex string>. Alternatively if you can't get it to work try email/password.
